from pathlib import Path
import re

path = Path('src/lib/people-data.ts')
text = path.read_text(encoding='utf-8')

new_block = '''export const departmentOptions = ['SDM', 'Teknologi', 'Penjualan', 'Keuangan', 'Produk', 'Hukum', 'Layanan Pelanggan'];
export const positionOptions = ['Generalist SDM', 'Manajer SDM', 'Pengembang Perangkat Lunak', 'Kepala Penjualan', 'Analis Produk', 'Desainer Produk', 'Konsultan Hukum', 'Direktur Layanan Pelanggan', 'Manajer Keuangan'];
export const statusOptions = ['Aktif', 'Cuti', 'Kontrak', 'Probation', 'Magang'];
export const contractOptions = ['Permanen', 'Waktu tertentu', 'Magang'];
export const branchOptions = ['Jakarta HQ', 'Surabaya Office', 'Bali Hub', 'Bandung Studio'];
export const locationOptions = ['Jakarta', 'Surabaya', 'Denpasar', 'Bandung', 'Remote'];
export const genderOptions = ['Perempuan', 'Laki-laki', 'Non-biner'];

export const employeeDirectory: EmployeeRecord[] = [
  {
    id: 'maya-sari',
    employeeId: 'EMP-1012',
    firstName: 'Maya',
    lastName: 'Sari',
    fullName: 'Maya Sari',
    photo: 'MS',
    initials: 'MS',
    department: 'SDM',
    position: 'Generalist SDM',
    status: 'Aktif',
    joinDate: '2021-04-12',
    contractType: 'Permanen',
    branch: 'Jakarta HQ',
    location: 'Jakarta',
    gender: 'Perempuan',
    manager: 'Noor Fadhila',
    lastActivity: '2 jam lalu',
    email: 'maya.sari@indocater.co.id',
    phone: '+62 812-3456-7890',
    office: 'Tower A, Lt. 11',
  },
  {
    id: 'leo-wibowo',
    employeeId: 'EMP-1006',
    firstName: 'Leo',
    lastName: 'Wibowo',
    fullName: 'Leo Wibowo',
    photo: 'LW',
    initials: 'LW',
    department: 'Teknologi',
    position: 'Pengembang Perangkat Lunak',
    status: 'Aktif',
    joinDate: '2022-01-19',
    contractType: 'Permanen',
    branch: 'Bandung Studio',
    location: 'Bandung',
    gender: 'Laki-laki',
    manager: 'Fitri Novita',
    lastActivity: 'Hari ini',
    email: 'leo.wibowo@indocater.co.id',
    phone: '+62 812-9988-2233',
    office: 'Bandung Studio Lt. 6',
  },
  {
    id: 'aulia-rizky',
    employeeId: 'EMP-1074',
    firstName: 'Aulia',
    lastName: 'Rizky',
    fullName: 'Aulia Rizky',
    photo: 'AR',
    initials: 'AR',
    department: 'Penjualan',
    position: 'Kepala Penjualan',
    status: 'Aktif',
    joinDate: '2020-09-03',
    contractType: 'Permanen',
    branch: 'Surabaya Office',
    location: 'Surabaya',
    gender: 'Perempuan',
    manager: 'Noor Fadhila',
    lastActivity: 'Kemarin',
    email: 'aulia.rizky@indocater.co.id',
    phone: '+62 811-2233-4455',
    office: 'Surabaya Plaza Lt. 2',
  },
  {
    id: 'zara-nurhidayah',
    employeeId: 'EMP-1031',
    firstName: 'Zara',
    lastName: 'Nurhidayah',
    fullName: 'Zara Nurhidayah',
    photo: 'ZN',
    initials: 'ZN',
    department: 'Produk',
    position: 'Desainer Produk',
    status: 'Cuti',
    joinDate: '2019-06-28',
    contractType: 'Permanen',
    branch: 'Bali Hub',
    location: 'Denpasar',
    gender: 'Perempuan',
    manager: 'Maya Sari',
    lastActivity: '3 hari lalu',
    email: 'zara.nurhidayah@indocater.co.id',
    phone: '+62 812-5567-8910',
    office: 'Bali Creative Space Lt. 3',
  },
  {
    id: 'noor-fadhila',
    employeeId: 'EMP-1020',
    firstName: 'Noor',
    lastName: 'Fadhila',
    fullName: 'Noor Fadhila',
    photo: 'NF',
    initials: 'NF',
    department: 'SDM',
    position: 'Manajer SDM',
    status: 'Aktif',
    joinDate: '2017-11-15',
    contractType: 'Permanen',
    branch: 'Jakarta HQ',
    location: 'Jakarta',
    gender: 'Laki-laki',
    manager: 'Dewi Lestari',
    lastActivity: 'Hari ini',
    email: 'noor.fadhila@indocater.co.id',
    phone: '+62 811-3344-5566',
    office: 'Tower B, Lt. 8',
  },
  {
    id: 'lia-pratiwi',
    employeeId: 'EMP-1088',
    firstName: 'Lia',
    lastName: 'Pratiwi',
    fullName: 'Lia Pratiwi',
    photo: 'LP',
    initials: 'LP',
    department: 'Layanan Pelanggan',
    position: 'Direktur Layanan Pelanggan',
    status: 'Aktif',
    joinDate: '2021-12-05',
    contractType: 'Permanen',
    branch: 'Remote',
    location: 'Remote',
    gender: 'Perempuan',
    manager: 'Noor Fadhila',
    lastActivity: '4 jam lalu',
    email: 'lia.pratiwi@indocater.co.id',
    phone: '+62 811-555-2233',
    office: 'Remote',
  },
  {
    id: 'caleb-santoso',
    employeeId: 'EMP-1105',
    firstName: 'Caleb',
    lastName: 'Santoso',
    fullName: 'Caleb Santoso',
    photo: 'CS',
    initials: 'CS',
    department: 'Keuangan',
    position: 'Manajer Keuangan',
    status: 'Aktif',
    joinDate: '2018-03-20',
    contractType: 'Permanen',
    branch: 'Bandung Studio',
    location: 'Bandung',
    gender: 'Laki-laki',
    manager: 'Dewi Lestari',
    lastActivity: 'Hari ini',
    email: 'caleb.santoso@indocater.co.id',
    phone: '+62 811-9988-5544',
    office: 'Bandung Studio Lt. 5',
  },
  {
    id: 'juni-rahmawati',
    employeeId: 'EMP-1112',
    firstName: 'Juni',
    lastName: 'Rahmawati',
    fullName: 'Juni Rahmawati',
    photo: 'JR',
    initials: 'JR',
    department: 'Hukum',
    position: 'Konsultan Hukum',
    status: 'Aktif',
    joinDate: '2020-02-14',
    contractType: 'Waktu tertentu',
    branch: 'Jakarta HQ',
    location: 'Jakarta',
    gender: 'Perempuan',
    manager: 'Noor Fadhila',
    lastActivity: '1 minggu lalu',
    email: 'juni.rahmawati@indocater.co.id',
    phone: '+62 811-2233-9988',
    office: 'Tower A, Lt. 4',
  },
  {
    id: 'emily-putri',
    employeeId: 'EMP-1123',
    firstName: 'Emily',
    lastName: 'Putri',
    fullName: 'Emily Putri',
    photo: 'EP',
    initials: 'EP',
    department: 'Teknologi',
    position: 'Pengembang Perangkat Lunak',
    status: 'Magang',
    joinDate: '2024-02-01',
    contractType: 'Magang',
    branch: 'Jakarta HQ',
    location: 'Jakarta',
    gender: 'Perempuan',
    manager: 'Leo Wibowo',
    lastActivity: 'Hari ini',
    email: 'emily.putri@indocater.co.id',
    phone: '+62 813-9988-2233',
    office: 'Tower A, Lt. 6',
  },
  {
    id: 'sophia-septiani',
    employeeId: 'EMP-1141',
    firstName: 'Sophia',
    lastName: 'Septiani',
    fullName: 'Sophia Septiani',
    photo: 'SS',
    initials: 'SS',
    department: 'Produk',
    position: 'Analis Produk',
    status: 'Aktif',
    joinDate: '2023-08-07',
    contractType: 'Permanen',
    branch: 'Jakarta HQ',
    location: 'Jakarta',
    gender: 'Perempuan',
    manager: 'Zara Nurhidayah',
    lastActivity: '5 jam lalu',
    email: 'sophia.septiani@indocater.co.id',
    phone: '+62 811-555-7801',
    office: 'Tower B, Lt. 7',
  },
];

export type EmployeeProfile = {
'''

match = re.search(r'export const departmentOptions = \[.*?\];\nexport const positionOptions = \[.*?\];\nexport const statusOptions = \[.*?\];\nexport const contractOptions = \[.*?\];\nexport const branchOptions = \[.*?\];\nexport const locationOptions = \[.*?\];\nexport const genderOptions = \[.*?\];\n\nexport const employeeDirectory: EmployeeRecord\[\] = \[.*?\];\n\nexport type EmployeeProfile = \{', text, flags=re.S)
if not match:
    raise SystemExit('Could not find the expected block in people-data.ts')
start, end = match.span()
text = text[:start] + new_block + text[end-1:]
path.write_text(text, encoding='utf-8')
print('updated people-data.ts (options and directory)')
